server:
  port: 8888

spring:
  application:
    name: PAYMENT-SERVICE
    
eureka:
  cliente:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
